# Generated by Django 3.2.9 on 2022-02-22 20:31

from django.db import migrations, models
import shortuuidfield.fields
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPayment',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('state', models.BooleanField(default=True, verbose_name='Deleted')),
                ('created_date', models.DateField(blank=True, editable=False, verbose_name='Created Date')),
                ('modified_date', models.DateField(blank=True, editable=False, verbose_name='Updated Date')),
                ('deleted_date', models.DateField(blank=True, editable=False, verbose_name='Deleted Date')),
                ('uuid', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22)),
                ('payment_method', models.CharField(choices=[('CREDIT_CARD', 'Credit Card'), ('CASH', 'Cash'), ('PAYPAL', 'Paypal')], max_length=20, verbose_name='Reservation State')),
                ('taxes', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Taxes')),
                ('room_charge', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Room Charge')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total')),
                ('payment_date', models.DateField(blank=True, editable=False, verbose_name='Payment Date')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Payment',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Deleted')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Created Date')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Updated Date')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Deleted Date')),
                ('uuid', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22)),
                ('payment_method', models.CharField(choices=[('CREDIT_CARD', 'Credit Card'), ('CASH', 'Cash'), ('PAYPAL', 'Paypal')], max_length=20, verbose_name='Reservation State')),
                ('taxes', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Taxes')),
                ('room_charge', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Room Charge')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total')),
                ('payment_date', models.DateField(auto_now_add=True, verbose_name='Payment Date')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
            },
        ),
    ]
